// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDncr4stLlRtyW6e4CecP5aJwBqyMp9qds',
    appId: '1:180618100414:web:4b2ec79da0efd23c65a8ef',
    messagingSenderId: '180618100414',
    projectId: 'notella-app',
    authDomain: 'notella-app-66f03.firebaseapp.com',
    storageBucket: 'notella-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtD_Ao2U_wUXc1TC7kgo_gftx1QxlFePk',
    appId: '1:180618100414:android:279a375d4fe386e565a8ef',
    messagingSenderId: '180618100414',
    projectId: 'notella-app',
    storageBucket: 'notella-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1b_ONZBzMx-OOTv3tmIdQEenHF_SYEcI',
    appId: '1:180618100414:ios:fabb3faf5d8f864465a8ef',
    messagingSenderId: '180618100414',
    projectId: 'notella-app',
    storageBucket: 'notella-app.appspot.com',
    iosClientId: '180618100414-bn4kerv802tqf8mud2o7ffuj71olskb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.notella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1b_ONZBzMx-OOTv3tmIdQEenHF_SYEcI',
    appId: '1:180618100414:ios:fabb3faf5d8f864465a8ef',
    messagingSenderId: '180618100414',
    projectId: 'notella-app',
    storageBucket: 'notella-app.appspot.com',
    iosClientId: '180618100414-bn4kerv802tqf8mud2o7ffuj71olskb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.notella',
  );
}
